### ISSUE TITLE
Summary Statistics not fully loading

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Publishing-Statistics#10]
Taking a look at http://publishingstats.iatistandard.org/summary_stats.html - only a small number of exiting publishers are loads

http://publishingstats.iatistandard.org/timeliness.html seems to be the full set, however....

**Comment by andylolz** [comment]
I’m pretty sure this problem is caused by IATI/ckanext-iati#319.

**Comment by andylolz** [comment]
This issue is caused by IATI/ckanext-iati#319.

**Comment by stevieflow** [comment]
Thanks @andylolz 

Is anyone in the IATI secretariat able to resolve this?  The concern is that the longer this occurs, then less stats are available.

**Comment by PetyaKangalova** [comment]
Thanks- we have asked Derilinx to look into the issue as a matter of priority and respond to the issue directly. We'll update you once fixed.

**Comment by andylolz** [comment]
I think this PR (IATI/IATI-Registry-Refresher#30) will help the registry refresher deal with registry rate limiting. The dashboard and publishing stats both rely on the registry refresher. So fixing the problem there will fix the problem here (once it’s deployed).

I think it’s okay that the registry API rate limits requests. It would be good to document it, though, which could perhaps be addressed as part of the current phase of work to improve the registry API docs.

**Comment by PetyaKangalova** [comment]
Brief update on this issue. Our devs have looked at the Bash processes which did not look healthy and yesterday they:

- Rebooted the box 
- Started a new full run 
 
Which has brought back missing publishers in the summary stats page.

**Comment by andylolz** [comment]
I think derilinx have currently disabled rate limiting on the registry, which I think has helped resolve this issue.

If there’s a plan to re-enable rate limiting (or indeed to make the dashboard and publisher stats more robust to registry API problems) it would be good if someone could take a look at IATI/IATI-Registry-Refresher#30.

**Comment by andylolz** [comment]
Great news. Thanks for this update, @PetyaKangalova.

I think Derilinx have [disabled rate limiting on the registry](https://github.com/IATI/ckanext-iati/issues/319#issuecomment-771823784) “for now”, which I think has helped resolve this issue.

If there’s a plan to re-enable rate limiting (or indeed to make the dashboard and publisher stats more robust to registry API problems) it would be good if someone could take a look at IATI/IATI-Registry-Refresher#30.

**Comment by akmiller01** [comment]
This appears resolved.
