### ISSUE TITLE
Footer link to github repo

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Publishing-Statistics#11]
The footer link from http://publishingstats.iatistandard.org/ points to 

https://github.com/IATI/IATI-Dashboard/issues?state=open

Should that not be this repo?

**Comment by andylolz** [comment]
Yes, that’s right. The footer for [publishingstats](http://publishingstats.iatistandard.org/) lives here:
https://github.com/IATI/IATI-Publishing-Statistics/blob/edb5b14a2382ec45aeac7b8e10995a7ac7fc6774/IATI-Dashboard/static/templates/base.html#L189-L201
